LB-Elterngespräch/backend/app/controllers/dashboard.py
from flask import Blueprint, render_template, redirect, url_for, flash, request
from flask_login import login_required, current_user
from model.models import Termin, db
from forms.ElterngespraechTerminForm import ElterngespraechTerminForm
from forms.DeleteTerminForm import DeleteTerminForm
from forms.EditUserForm import EditUserForm
from model.models import User, db


# Blueprint for admin dashboard
admin_dashboard_blueprint = Blueprint('admin_dashboard_blueprint', __name__)

@admin_dashboard_blueprint.route("/admin/dashboard", methods=["GET"])
@login_required
def admin_dashboard():
    if current_user.role != "admin":
        flash("Access denied!", "danger")
        return redirect(url_for('index_blueprint.index'))
    return render_template('dashboards/admin_dashboard.html')

@admin_dashboard_blueprint.route("/admin/dashboard/termine", methods=["GET"])
@login_required
def admin_manage_termine():
    if current_user.role != "admin":
        flash("Access denied!", "danger")
        return redirect(url_for('index_blueprint.index'))

    termine = Termin.query.all()
    delete_form = DeleteTerminForm()  # Initialisiere das Formular
    return render_template('termin/admin_manage_termine.html', termine=termine, form=delete_form)



@admin_dashboard_blueprint.route("/admin/dashboard/users", methods=["GET"])
@login_required
def manage_users():
    if current_user.role != "admin":
        flash("Access denied!", "danger")
        return redirect(url_for('index_blueprint.index'))

    users = User.query.all()
    return render_template('users/manage_users.html', users=users)


@admin_dashboard_blueprint.route("/admin/dashboard/edit_user/<int:user_id>", methods=["GET", "POST"])
@login_required
def edit_user(user_id):
    if current_user.role != "admin":
        flash("Access denied!", "danger")
        return redirect(url_for('index_blueprint.index'))

    user = User.query.get(user_id)
    if not user:
        flash("User not found.", "danger")
        return redirect(url_for('admin_dashboard_blueprint.manage_users'))

    form = EditUserForm(obj=user)
    if form.validate_on_submit():
        user.username = form.username.data.strip()
        user.role = form.role.data
        db.session.commit()
        flash("User successfully updated!", "success")
        return redirect(url_for('admin_dashboard_blueprint.manage_users'))

    return render_template('users/edit_user.html', form=form, user=user)


@admin_dashboard_blueprint.route("/admin/dashboard/delete_user/<int:user_id>", methods=["POST"])
@login_required
def delete_user(user_id):
    if current_user.role != "admin":
        flash("Access denied!", "danger")
        return redirect(url_for('index_blueprint.index'))

    user = User.query.get(user_id)
    if not user:
        flash("User not found.", "danger")
        return redirect(url_for('admin_dashboard_blueprint.manage_users'))

    db.session.delete(user)
    db.session.commit()
    flash("User successfully deleted!", "success")
    return redirect(url_for('admin_dashboard_blueprint.manage_users'))

@admin_dashboard_blueprint.route("/admin/dashboard/create_termin", methods=["GET", "POST"])
@login_required
def create_termin():
    if current_user.role != "admin":
        flash("Access denied!", "danger")
        return redirect(url_for('index_blueprint.index'))

    form = ElterngespraechTerminForm()  # Passe an dein bestehendes Formularmodell an
    if form.validate_on_submit():
        new_termin = Termin(
            title=form.title.data,
            teacher_id=current_user.id,  # Der aktuell eingeloggte Lehrer wird verknüpft
            date=form.date.data,
            description=form.description.data,
            time=form.time.data
        )
        db.session.add(new_termin)
        db.session.commit()
        flash("Termin successfully created!", "success")
        return redirect(url_for('admin_dashboard_blueprint.admin_manage_termine'))


    return render_template("termin/create_termin.html", form=form)


@admin_dashboard_blueprint.route("/admin/dashboard/edit_termin/<int:termin_id>", methods=["GET", "POST"])
@login_required
def edit_termin(termin_id):
    if current_user.role != "admin":
        flash("Access denied!", "danger")
        return redirect(url_for('index_blueprint.index'))

    termin = Termin.query.filter_by(id=termin_id, teacher_id=current_user.id).first()
    if not termin:
        flash("Termin not found or access denied.", "danger")
        return redirect(url_for('admin_dashboard_blueprint.admin_manage_termine'))

    form = ElterngespraechTerminForm(obj=termin)

    if form.validate_on_submit():
        termin.title = form.title.data.strip()
        termin.date = form.date.data
        termin.time = form.time.data
        termin.description = form.description.data.strip() if form.description.data else None

        db.session.commit()
        flash("Termin successfully updated!", "success")
        return redirect(url_for('admin_dashboard_blueprint.admin_manage_termine'))

    return render_template("termin/edit_termin.html", form=form, termin=termin)


@admin_dashboard_blueprint.route("/admin/dashboard/delete_termin/<int:termin_id>", methods=["POST"])
@login_required
def delete_termin(termin_id):
    if current_user.role not in ["admin", "teacher"]:
        flash("Access denied!", "danger")
        return redirect(url_for('index_blueprint.index'))

    form = DeleteTerminForm(request.form)
    if not form.validate_on_submit():
        flash("Invalid CSRF token.", "danger")
        return redirect(url_for('admin_dashboard_blueprint.admin_manage_termine'))

    if current_user.role == "admin":
        termin = Termin.query.get(termin_id)  # Admin darf alle Termine löschen
    else:
        termin = Termin.query.filter_by(id=termin_id, teacher_id=current_user.id).first()  # Lehrer nur ihre eigenen

    if not termin:
        flash("Termin not found or access denied.", "danger")
        return redirect(url_for('admin_dashboard_blueprint.admin_manage_termine'))

    db.session.delete(termin)
    db.session.commit()
    flash("Termin successfully deleted!", "success")
    return redirect(url_for('admin_dashboard_blueprint.admin_manage_termine'))


@admin_dashboard_blueprint.route("/admin/dashboard/create_termin", methods=["GET", "POST"])
@login_required
def admin_create_termin():
    if current_user.role != "admin":
        flash("Access denied!", "danger")
        return redirect(url_for('index_blueprint.index'))

    form = ElterngespraechTerminForm()
    if form.validate_on_submit():
        new_termin = Termin(
            title=form.title.data,
            teacher_id=form.teacher_id.data,  # Admins können Lehrer zuweisen
            date=form.date.data,
            time=form.time.data,
            description=form.description.data
        )
        db.session.add(new_termin)
        db.session.commit()
        flash("Termin successfully created!", "succe    ss")
        return redirect(url_for('admin_dashboard_blueprint.admin_manage_termine'))

    return render_template("termin/create_termin.html", form=form)



# Blueprint for teacher dashboard
teacher_dashboard_blueprint = Blueprint('teacher_dashboard_blueprint', __name__)

@teacher_dashboard_blueprint.route("/teacher/dashboard", methods=["GET"])
@login_required
def teacher_dashboard():
    if current_user.role != "teacher":
        flash("Access denied!", "danger")
        return redirect(url_for('index_blueprint.index'))

    # Nur Termine des aktuellen Lehrers abrufen
    termine = Termin.query.filter_by(teacher_id=current_user.id).all()
    delete_form = DeleteTerminForm()  # Initialisiere das Formular
    return render_template('dashboards/teacher_dashboard.html', termine=termine, delete_form=delete_form)


@teacher_dashboard_blueprint.route("/teacher/dashboard/create_termin", methods=["GET", "POST"])
@login_required
def create_termin():
    if current_user.role != "teacher":
        flash("Access denied!", "danger")
        return redirect(url_for('index_blueprint.index'))

    form = ElterngespraechTerminForm()  # Passe an dein bestehendes Formularmodell an
    if form.validate_on_submit():
        new_termin = Termin(
            title=form.title.data,
            teacher_id=current_user.id,  # Der aktuell eingeloggte Lehrer wird verknüpft
            date=form.date.data,
            description=form.description.data,
            time=form.time.data
        )
        db.session.add(new_termin)
        db.session.commit()
        flash("Termin successfully created!", "success")
        return redirect(url_for('teacher_dashboard_blueprint.teacher_dashboard'))

    return render_template("termin/create_termin.html", form=form)


@teacher_dashboard_blueprint.route("/teacher/dashboard/edit_termin/<int:termin_id>", methods=["GET", "POST"])
@login_required
def edit_termin(termin_id):
    if current_user.role != "teacher":
        flash("Access denied!", "danger")
        return redirect(url_for('index_blueprint.index'))

    termin = Termin.query.filter_by(id=termin_id, teacher_id=current_user.id).first()
    if not termin:
        flash("Termin not found or access denied.", "danger")
        return redirect(url_for('teacher_dashboard_blueprint.teacher_dashboard'))

    form = ElterngespraechTerminForm(obj=termin)

    if form.validate_on_submit():
        termin.title = form.title.data.strip()
        termin.date = form.date.data
        termin.time = form.time.data
        termin.description = form.description.data.strip() if form.description.data else None

        db.session.commit()
        flash("Termin successfully updated!", "success")
        return redirect(url_for('teacher_dashboard_blueprint.teacher_dashboard'))

    return render_template("termin/edit_termin.html", form=form, termin=termin)


@teacher_dashboard_blueprint.route("/teacher/dashboard/delete_termin/<int:termin_id>", methods=["POST"])
@login_required
def delete_termin(termin_id):
    if current_user.role != "teacher":

LB-Elterngespräch/backend/app/controllers/help.py
from flask import Blueprint, render_template

# Blueprint für Help-Seite
help_blueprint = Blueprint('help_blueprint', __name__)

@help_blueprint.route("/help", methods=["GET"])
def help():
    """
    Zeigt eine statische Hilfeseite an.
    """
    return render_template('help.html')

LB-Elterngespräch/backend/app/controllers/user.py
import sqlalchemy
import sqlalchemy.orm

from flask import redirect, request, flash, url_for
from flask.templating import render_template
from flask_login import UserMixin, login_user, LoginManager, login_required, logout_user, current_user
from flask import Blueprint
from forms.UserForm import RegisterForm
from forms.UserForm import LoginForm
from model.models import User, db
from flask_bcrypt import Bcrypt
from controllers.decorater import requires_access_level
from model.ACCESS import ACCESS

bcrypt = Bcrypt()

users_blueprint = Blueprint('users_blueprint', __name__)

@users_blueprint.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user:
            if bcrypt.check_password_hash(user.password, form.password.data):
                login_user(user)
                flash("Successfully logged in!", "success")
                return redirect(url_for('users_blueprint.dashboard'))
            else:
                flash("Invalid username or password", "danger")
        else:
            flash("User not found", "warning")
    return render_template('login.html', form=form)


@users_blueprint.route("/dashboard", methods=["GET"])
@requires_access_level(ACCESS['guest'])
def dashboard():
    return render_template('dashboard.html')


@users_blueprint.route("/logout", methods=["GET"])
@login_required
def logout():
    logout_user()
    flash("You have been logged out.", "info")
    return redirect(url_for('users_blueprint.login'))


@users_blueprint.route("/register", methods=["GET", "POST"])
def register():
    form = RegisterForm()

    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user:
            flash("Username already exists", "danger")
        else:
            hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
            new_user = User(username=form.username.data, password=hashed_password)
            db.session.add(new_user)
            db.session.commit()
            flash("Registration successful! You can now log in.", "success")
            return redirect(url_for('users_blueprint.login'))

    return render_template('register.html', form=form)

LB-Elterngespräch/backend/app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Home-Page</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous" />
  <style>
    body {
      padding: 0px;
    }
    .hr {
      padding: 0px;
      margin: 0px;
    }
    #bzt-image {
      background-image: url("/static/images/leadbild_bzt.jpg");
      background-size: cover; /* Adjust this if necessary */
      background-repeat: no-repeat;
      background-position: center;
      padding: 9rem; /* Increase padding for more space inside */
      margin-top: 10rem; /* Optional: increase margin */
      font-size: 1.5rem; /* Increase font size for larger text */
      color: white;
      height: 400px;
    }

    .outlined-text {
      color: white; /* Textfarbe */
      text-shadow: 
        -1px -1px 0 black, /* Oben links */
        1px -1px 0 black, /* Oben rechts */
        -1px  1px 0 black, /* Unten links */
        1px  1px 0 black; /* Unten rechts */
    }


  </style>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <!-- Left-aligned Links -->
      <div class="collapse navbar-collapse">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Home</a>
          </li>
          {% if not current_user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link active" href="/login">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="/register">Sign Up</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link active" href="{{ url_for('users_blueprint.logout') }}">Logout</a>
            </li>
          {% endif %}
        </ul>
      </div>

      <!-- Right-aligned Help Button -->
      <div class="d-flex">
        <a class="nav-link active" href="/help" role="button">
          <span❔</span> Help
        </a>
      </div>
    </div>
  </nav>
  <hr class="hr">

  <!-- User role-specific navigation links -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <div class="collapse navbar-collapse">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          {% if current_user.is_authenticated %}
            {% if current_user.role == "admin" %}
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('admin_dashboard_blueprint.admin_dashboard') }}">Admin Dashboard</a>
              </li>
            {% elif current_user.role == "teacher" %}
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('teacher_dashboard_blueprint.teacher_dashboard') }}">Teacher Dashboard</a>
              </li>
            {% elif current_user.role == "parent" %}
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('parent_dashboard_blueprint.parent_dashboard') }}">Parent Dashboard</a>
              </li>
            {% endif %}
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  {% with messages = get_flashed_messages() %}
  {% if messages %}
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    {% for message in messages %}
    {{ message }}
    {% endfor %}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
  {% endif %}
  {% endwith %}

  {%block body%} {%endblock%}

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
    crossorigin="anonymous"></script>

  <script src="/static/classicmodels.js"></script>
</body>

</html>

LB-Elterngespräch/backend/app/templates/dashboard.html
{% extends 'dashboard_base.html' %}

{% block title %}
    dashborad
{% endblock %}

{% block body %}
<div class="container mt-3">
    <a href="/termine" class="btn termin-verinbaren">Termin Vereinbaren</a>
    <a href="/termin-verschieben" class="btn termin-verschieben">Termin Verschieben</a>
    <a href="/termin-anzeigen" class="btn termin-anzeigen">Termin Anzeigen</a>    
</div>

<style>
    .btn {
      display: inline-block; /* Button-ähnliches Verhalten */
      padding: 10px 20px;
      background-color: #007bff; /* Bootstrap blaue Button-Farbe */
      color: white;
      text-decoration: none; /* Entfernt die Unterstreichung */
      border-radius: 5px;
      margin: 5px; /* Abstand zwischen den Buttons */
    }
  
    .btn:hover {
      background-color: #0056b3; /* Dunklere Farbe beim Hover */
    }
  </style>
{% endblock %}

LB-Elterngespräch/backend/app/templates/help.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Help</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>

<body>
  <div class="container mt-5">
    <h1 class="mb-4">Help & Instructions</h1>
    <p>Welcome to the Help page! Here you can find instructions on how to use the application:</p>
    <ul>
      <li>To log in, click on the <strong>Login</strong> button in the navigation bar and enter your credentials.</li>
      <li>To register, click on the <strong>Sign Up</strong> button and fill out the registration form.</li>
      <li>If you encounter any issues, please contact support at <a href="mailto:support@example.com">support@example.com</a>.</li>
    </ul>
    <a href="/" class="btn btn-primary mt-3">Back to Home</a>
  </div>
</body>

</html>

LB-Elterngespräch/backend/app/templates/index.html
{%extends 'base.html'%}

{%block body%}

<div class="mt-0" id="bzt-image">
  <h1 class="outlined-text">Willkomen auf der Website für Termine des Elterngesprächs</h1>
  <p class="outlined-text">Eine Website des BZT's</p>
</div>


{%endblock%}

LB-Elterngespräch/backend/app/templates/login.html
{% extends 'base.html' %}
{% block title %}
    login
{% endblock %}
{% block body %}
<div class="container mt-3">

    <h2 class="text-primary text-center">Login page</h2>
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">UserName</label>
            {{ form.username(class_='form-control') }}
            
          </div>
          <div class="mb-3">
            <label for="exampleInputPassword1" class="form-label">Password</label>
            
            {{ form.password(class_='form-control') }}
          </div>
        {{ form.submit(class_='btn btn-primary') }}
    </form>
      
      
        
    
    <p>Don't have an account? <a href="/register">Sign up</a></p>
</div>
{% endblock %}

LB-Elterngespräch/backend/app/templates/register.html
{% extends 'base.html' %}
{% block title %}
    register
{% endblock %}

{% block body %}
<div class="container mt-3">

    <h2 class="text-center text-primary">Register</h2>
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">UserName</label>
            {{ form.username(class_='form-control') }}
          </div>
          <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Password</label>
            {{ form.password(class_='form-control') }}
          </div>

        {{ form.submit(class_='btn btn-primary')}}
    </form>
    
    
    <p>Already have an account? <a class="btn btn-outline-primary" href="/login">Login</a></p>
</div>
{% endblock %}